### PR TITLE
Fix for squid:s1199

### PR DESCRIPTION
**Pull request by alainlompo**

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
I'm guessing this is for https://sonarcloud.io/organizations/default/rules#rule_key=squid%3AS1199 etc

This would be an improvement if all the other implementations were updated accordingly. Otherwise I'm afraid this would make maintenance harder. See https://github.com/cucumber/cucumber/blob/master/gherkin/CONTRIBUTING.md#consistency-between-implementations

Would you be willing to make this change in all the other Gherkin implementations @alainlompo ?

**Comment by alainlompo** [comment]
@ahhbristow ,
Thank you for your answer. Sure it would be my pleasure to implement this change everywhere else. More on this soon.

**Comment by aslakhellesoy** [comment]
Brilliant - I recommend making the pull request in the [monorepo](https://github.com/cucumber/cucumber/tree/master/gherkin) rather than the various gherkin-* repos. We try to do development there - the gherkin-* repositories are only used to make releases, and for users to consume.

**Comment by alainlompo** [comment]
OK, thank you. I forked it and will soon create the pull request there

**Comment by alainlompo** [comment]
@aslakhellesoy 
I am furthering the fix implementations on [following fork](https://github.com/alainlompo/cucumber), (starting with java gherking module) before creating a new pool request. The attached file shows a few violations.

sonarlint-violations

AttachmentEvent.java shows many unused private fields. Is this some work in progress, or why are they needed?

Parser.java shows a lot of violations but is a generated class, which obviously cannot be directly fixed since the next generation would undo the fixes.

**Comment by aslakhellesoy** [comment]
AttachmentEvent is a struct which is only used for JSON generation. The fields are only accessed via reflection.

Is your plan to make all the changes in the Java implementation and then port the relevant changes to Ruby, JavaScript, Python, C#, Go etc?

**Comment by alainlompo** [comment]
**AttachmentEvent is a struct which is only used for JSON generation. The fields are only accessed via reflection.**
==> OK, understood.


**Is your plan to make all the changes in the Java implementation and then port the relevant changes to Ruby, JavaScript, Python, C#, Go etc?**
==> That sounds like a great plan but it will take some time. I therefore suggest to start with java, but yes it would be very interesting to go ahead and bring the changes to the other languages

**Comment by aslakhellesoy** [comment]
Currently, the various language implementations have a very similar structure. Making structural changes in some implementations and not in others would cause their structures to diverge. This would lead to harder maintenance, as described [here](https://github.com/cucumber/cucumber/blob/master/gherkin/CONTRIBUTING.md#consistency-between-implementations).

For this reason we can only accept a pull request which would maintain the consistency between implementations.

The changes would be very welcome, but I'm concerned that it is hard to do because there are so many languages involved.

I would only proceed if you think you'll be able to update all languages.

**Comment by aslakhellesoy** [comment]
I'm closing this pull request since a new effort is currently happening over in https://github.com/alainlompo/cucumber

**Pull request closed without merging**
